### PR TITLE
Support for custom links and fixed fetch issue

### PR DESCRIPTION
**Pull request by juicycleff**

### CODE REVIEW

**Comment by juicycleff** [comment]
This PR solves issues with session cookie even after specifying the Apollo credentials token when not using same-site mode. Also, there is support for custom links that can be merged into the default connection link

Here is the usage

```Flow
// my-apollo-links.js
// @flow
import {onError} from 'apollo-link-error';

const linkError = onError(({graphQLErrors, networkError}) => {
  if (graphQLErrors) {
    graphQLErrors.forEach(({message, locations, path}) =>
      console.log(
        `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`
      )
    );

    const unAuth =
      graphQLErrors && graphQLErrors.reduce(mess => mess.statusCode === 403);
    if (unAuth) {
      // dispatch(loginUserAction({isLoggedIn: false}));
    } else {
      // dispatch(loginUserAction({isLoggedIn: true}));
    }
  }
  if (networkError) console.log(`[Network error]: ${networkError}`);

  console.log(graphQLErrors);
  console.log(networkError);
});

export const graphqlLinks = [linkError];

// main.js
app.register(ApolloCustomLinksToken, graphqlLinks);

```

**Comment by chrisdothtml** [comment]
@juicycleff [looks like](https://buildkite.com/uberopensource/fusionjs/builds/750#5d4e0850-ce7a-435c-a495-20462c9785da/100-197) you have some lint errors. Can you fix those?

**Comment by juicycleff** [comment]
@chrisdothtml yeah I noticed. Fixed the lint errors :)

**Comment by ganemone** [comment]
It seems like this could be handled with the existing `GetApolloClientLinksToken`.

**Comment by ganemone** [comment]
Going to close the PR since this duplicates functionality of the the existing `GetApolloClientsLinksToken` but if you have concerns feel free to reopen and we can discuss.

**Pull request closed without merging**
