### PR TITLE
Add support for default options config

### LINKED ISSUE #688: Adding support for default options configuration in fusion-plugin-apollo.
Can we add support for default options config to be passed to apollo server constructor. The config object will have following properties. 

{|
introspection
playground
debug
validationRules
formatError
formatResponse
cors
|}

### PR DESCRIPTION
**Pull request by joginder07**
Resolves #688 

Added a new token 'ApolloDefaultOptionsConfigToken' to allow default options config.

### CODE REVIEW

**Comment by ganemone** [comment]
This looks good. Could you write a test of some kind?

**Comment by joginder07** [comment]
Sure, i will add.

**Comment by joginder07** [comment]
@ganemone , added test.

**Comment by ganemone** [comment]
!import

**Pull request closed without merging**
